"""empty message

Revision ID: e1548647b134
Revises: 
Create Date: 2020-09-24 14:25:40.263316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1548647b134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_video_game_sales', 'EU_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment=None,
               existing_comment='欧美区域销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Genre',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='游戏类型',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Global_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment=None,
               existing_comment='全球销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'JP_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment=None,
               existing_comment='日本区域销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'NA_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment=None,
               existing_comment='北美区域销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='游戏名称',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Other_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment=None,
               existing_comment='其他国家销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Platform',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='该游戏发布平台',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Publisher',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='出版公司',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Rank',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='销售排名')
    op.alter_column('t_video_game_sales', 'Year',
               existing_type=mysql.INTEGER(display_width=255),
               comment=None,
               existing_comment='发布年份（1980~2016）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_video_game_sales', 'Year',
               existing_type=mysql.INTEGER(display_width=255),
               comment='发布年份（1980~2016）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Rank',
               existing_type=mysql.VARCHAR(length=255),
               comment='销售排名')
    op.alter_column('t_video_game_sales', 'Publisher',
               existing_type=mysql.VARCHAR(length=255),
               comment='出版公司',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Platform',
               existing_type=mysql.VARCHAR(length=255),
               comment='该游戏发布平台',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Other_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment='其他国家销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Name',
               existing_type=mysql.VARCHAR(length=255),
               comment='游戏名称',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'NA_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment='北美区域销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'JP_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment='日本区域销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Global_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment='全球销量（以百万为单位计数）',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'Genre',
               existing_type=mysql.VARCHAR(length=255),
               comment='游戏类型',
               existing_nullable=True)
    op.alter_column('t_video_game_sales', 'EU_Sales',
               existing_type=mysql.DOUBLE(precision=255, scale=2, asdecimal=True),
               comment='欧美区域销量（以百万为单位计数）',
               existing_nullable=True)
    # ### end Alembic commands ###
